const express = require('express');
const app = express();
const helmet =require('helmet');
const morgan = require('morgan');
const cors = require('cors');
const usersRoutes = require('./routes/user');
const postsRoutes = require('./routes/post');
const commentaryRoutes = require('./routes/commentary');
app.use(morgan('dev'));
app.use(cors());
app.use(helmet());
app.use(express.json());
app.use('/api/users', usersRoutes);
app.use('/api/posts', postsRoutes);
app.use('/api/commentary', commentaryRoutes);
module.exports = app;